name: Build Anime-Sama Ultra ğŸŒ®

on:
  workflow_dispatch:

# ğŸ‘‡ AJOUT IMPORTANT : On donne les permissions au robot
permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: ğŸ“¥ RÃ©cupÃ©ration du Code
        uses: actions/checkout@v4

      - name: ğŸ’¿ Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸŒ¯ Installation des IngrÃ©dients
        run: npm install

      - name: ğŸ³ Cuisine (Build)
        # ğŸ‘‡ C'EST ICI LA CORRECTION MAGIQUE ğŸ‘‡
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ğŸ‘† FIN DE LA CORRECTION ğŸ‘†
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            npm run dist -- --win
          else
            npm run dist -- --mac
          fi
        shell: bash

      - name: ğŸ“¦ Envoi du Colis (Upload)
        uses: actions/upload-artifact@v4
        with:
          name: App-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
